# Generated by Django 5.2.9 on 2026-01-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원 목록'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=50, verbose_name='신뢰 점수'),
        ),
    ]
