# Generated by Django 5.2.9 on 2026-04-02 16:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipment', '0037_jobpost_legacy_guin_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='상품코드')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('product_type', models.CharField(choices=[('PREMIUM_TOP', '프리미엄 상단 노출'), ('LISTING_UPGRADE', '판매글 업그레이드'), ('DEALER_MEMBERSHIP', '딜러 PRO 멤버십')], db_index=True, max_length=20, verbose_name='상품 유형')),
                ('slot_type', models.CharField(blank=True, choices=[('CATEGORY_TOP', '카테고리 상단'), ('REGION_TOP', '지역 상단'), ('SEARCH_MATCH', '검색조건 매칭 상단')], max_length=20, null=True, verbose_name='슬롯 타입 (프리미엄 상단용)')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='유효 일수')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='판매가')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='정기결제 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='판매 여부')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '요금제/상품',
                'verbose_name_plural': '요금제/상품',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='주문번호')),
                ('status', models.CharField(choices=[('PENDING', '결제 대기'), ('PAID', '결제 완료'), ('CANCELLED', '취소'), ('REFUNDED', '환불')], db_index=True, default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('admin_memo', models.TextField(blank=True, null=True, verbose_name='운영 메모')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='환불 금액')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='환불 처리 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='구매 시점 단가')),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('slot_type', models.CharField(blank=True, choices=[('CATEGORY_TOP', '카테고리 상단'), ('REGION_TOP', '지역 상단'), ('SEARCH_MATCH', '검색조건 매칭 상단')], max_length=20, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='확장 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.order')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_order_items', to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.product')),
            ],
            options={
                'verbose_name': '주문 항목',
                'verbose_name_plural': '주문 항목',
            },
        ),
        migrations.CreateModel(
            name='EquipmentUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_images', models.PositiveIntegerField(default=20, verbose_name='최대 사진 수')),
                ('is_highlight', models.BooleanField(default=True, verbose_name='강조 표시')),
                ('bump_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 재노출 시점')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade', to='equipment.equipment')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_upgrades', to='billing.orderitem')),
            ],
            options={
                'verbose_name': '매물 업그레이드',
                'verbose_name_plural': '매물 업그레이드',
            },
        ),
        migrations.CreateModel(
            name='DealerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='구독 시작일')),
                ('period_end', models.DateField(db_index=True, verbose_name='구독 만료일')),
                ('is_auto_renew', models.BooleanField(default=False, verbose_name='자동 갱신')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_membership', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_memberships', to='billing.orderitem')),
            ],
            options={
                'verbose_name': '딜러 PRO 멤버십',
                'verbose_name_plural': '딜러 PRO 멤버십',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_provider', models.CharField(max_length=20, verbose_name='PG사')),
                ('pg_tid', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='PG 거래 ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('REQUESTED', '요청됨'), ('SUCCESS', '성공'), ('FAILED', '실패'), ('CANCELLED', '취소')], db_index=True, default='REQUESTED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='PG 원문 응답')),
                ('admin_memo', models.TextField(blank=True, null=True, verbose_name='운영 메모')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='환불 금액')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='환불 처리 시각')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.order')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('product_code', models.CharField(db_index=True, max_length=32)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('amount_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '일별 매출',
                'verbose_name_plural': '일별 매출',
                'ordering': ['-date', 'product_code'],
                'unique_together': {('date', 'product_code')},
            },
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=32, verbose_name='이벤트 유형')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='추가 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_events', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '전환 이벤트',
                'verbose_name_plural': '전환 이벤트',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='billing_con_event_t_9b40a0_idx'), models.Index(fields=['user', 'created_at'], name='billing_con_user_id_64259d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PremiumPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', '대기'), ('ACTIVE', '활성'), ('EXPIRED', '만료'), ('REFUNDED', '환불')], db_index=True, default='WAITING', max_length=12, verbose_name='배치 상태')),
                ('slot_type', models.CharField(choices=[('CATEGORY_TOP', '카테고리 상단'), ('REGION_TOP', '지역 상단'), ('SEARCH_MATCH', '검색조건 매칭 상단')], db_index=True, max_length=20)),
                ('slot_no', models.PositiveSmallIntegerField(blank=True, help_text='CATEGORY_TOP일 때 1~5 고정 슬롯. NULL이면 대기열.', null=True, verbose_name='슬롯 번호(1~5)')),
                ('waitlist_rank', models.PositiveIntegerField(blank=True, help_text='표시용(정합성 원본은 paid_at ASC + id ASC).', null=True, verbose_name='대기열 순서')),
                ('category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('region_key', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('match_keywords', models.JSONField(blank=True, default=dict, help_text='SEARCH_MATCH: {"raw": [...], "norm": [...]}. 노출 로직은 norm 기준 매칭.', verbose_name='검색 매칭 키워드')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(db_index=True, help_text='공정 정렬(paid_at ASC). 결제 성공 시 Payment.paid_at 복사, null 불가.', verbose_name='결제 시각')),
                ('auto_renewable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('admin_memo', models.TextField(blank=True, null=True, verbose_name='운영 메모')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='환불 처리 시각')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='환불 금액')),
                ('period_adjusted_at', models.DateTimeField(blank=True, null=True, verbose_name='기간 수동 조정 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_placements', to='equipment.equipment')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='billing.orderitem')),
            ],
            options={
                'verbose_name': '프리미엄 상단 노출',
                'verbose_name_plural': '프리미엄 상단 노출',
                'ordering': ['paid_at', 'id'],
                'indexes': [models.Index(fields=['slot_type', 'expires_at'], name='billing_pre_slot_ty_9ad848_idx'), models.Index(fields=['slot_type', 'category', 'expires_at'], name='billing_pre_slot_ty_767348_idx'), models.Index(fields=['slot_type', 'region_key', 'expires_at'], name='billing_pre_slot_ty_81703b_idx'), models.Index(fields=['slot_type', 'category', 'slot_no'], name='billing_pre_slot_ty_c9a321_idx'), models.Index(fields=['slot_type', 'category', 'paid_at'], name='billing_pp_waitlist_paid'), models.Index(fields=['slot_type', 'category', 'slot_no', 'expires_at'], name='billing_pp_slot_exp')],
                'constraints': [models.CheckConstraint(condition=models.Q(('slot_no__isnull', True), models.Q(('slot_no__gte', 1), ('slot_no__lte', 5)), _connector='OR'), name='billing_pp_slot_no_range_1_5'), models.UniqueConstraint(condition=models.Q(('slot_no__isnull', False), ('slot_type', 'CATEGORY_TOP')), fields=('slot_type', 'category', 'slot_no'), name='billing_placement_category_slot_unique')],
            },
        ),
    ]
