# Generated by Django 5.2.9 on 2025-12-12 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='굴삭기', max_length=50)),
                ('tonnage_precise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tonnage_category', models.CharField(max_length=20)),
                ('op_type', models.CharField(choices=[('CR', '크롤러 (궤도식)'), ('WL', '휠 (타이어식)')], max_length=2)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('year_manufactured', models.IntegerField()),
                ('hours_used', models.IntegerField()),
                ('current_location', models.CharField(max_length=100)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_verified_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='users.user')),
            ],
        ),
    ]
