# Generated by Django 5.2.9 on 2025-12-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '중고 매물', 'verbose_name_plural': '중고 매물 관리'},
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipment_photos/%Y/%m/%d/', verbose_name='매물 사진')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment', verbose_name='해당 매물')),
            ],
            options={
                'verbose_name': '매물 사진',
                'verbose_name_plural': '매물 사진들',
            },
        ),
    ]
