# Generated by Django 5.2.9 on 2025-12-28 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_options_equipmentimage'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(default='굴삭기', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(max_length=100, verbose_name='지역(위치)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hours_used',
            field=models.IntegerField(verbose_name='가동 시간(h)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_verified_status',
            field=models.BooleanField(default=False, verbose_name='인증 상태'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='listing_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='판매 가격'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=50, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='모델명'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='op_type',
            field=models.CharField(choices=[('CR', '크롤러 (궤도식)'), ('WL', '휠 (타이어식)')], max_length=2, verbose_name='작동 방식'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='users.user', verbose_name='판매자'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tonnage_category',
            field=models.CharField(max_length=20, verbose_name='톤수 분류'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tonnage_precise',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='상세 톤수'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year_manufactured',
            field=models.IntegerField(verbose_name='제작 연식'),
        ),
    ]
