# Generated by Django 5.2.9 on 2026-01-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_category_alter_equipment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipmentimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='hours_used',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='is_verified_status',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='op_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tonnage_category',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tonnage_precise',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='equipmentimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='listing_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year_manufactured',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='image',
            field=models.ImageField(upload_to='equipment_photos/'),
        ),
    ]
