# Generated by Django 5.2.9 on 2026-01-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_options_alter_equipmentimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
    ]
