# Generated by Django 5.2.9 on 2026-01-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '매물', 'verbose_name_plural': '매물 관리'},
        ),
        migrations.AlterModelOptions(
            name='equipmentimage',
            options={'verbose_name': '장비사진', 'verbose_name_plural': '사진 관리'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='판매완료여부'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(max_length=100, verbose_name='현재위치'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='상세설명'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='listing_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='판매가격(만원)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='모델명'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='password',
            field=models.CharField(default='1234', max_length=20, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year_manufactured',
            field=models.IntegerField(verbose_name='연식'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='image',
            field=models.ImageField(upload_to='equipment_photos/', verbose_name='장비사진'),
        ),
    ]
