# Generated by Django 5.2.9 on 2026-01-04 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_equipment_options_alter_equipmentimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '매물', 'verbose_name_plural': '매물'},
        ),
        migrations.AlterModelOptions(
            name='equipmentimage',
            options={'verbose_name': '매물 이미지', 'verbose_name_plural': '매물 이미지'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(max_length=100, verbose_name='현재 위치'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(verbose_name='상세설명'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='판매완료'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='listing_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='판매가(만원)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=50, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='password',
            field=models.CharField(max_length=100, verbose_name='수정/삭제 비밀번호'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment', verbose_name='매물'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='image',
            field=models.ImageField(upload_to='equipment_images/', verbose_name='이미지'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('PERSONAL', '개인'), ('DEALER', '매매상')], default='PERSONAL', max_length=10, verbose_name='회원유형')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='상호명')),
                ('business_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='사업자등록번호')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인여부')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='유튜브 채널 주소')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필',
            },
        ),
    ]
