# Generated by Django 5.2.9 on 2026-01-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipment_options_alter_equipmentimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(verbose_name='상세 설명'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='판매 완료 여부'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='listing_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='판매가격(만원)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='password',
            field=models.CharField(max_length=100, verbose_name='비밀번호'),
        ),
    ]
