# Generated by Django 5.2.9 on 2026-01-04 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_description_alter_equipment_is_sold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '중고 굴삭기', 'verbose_name_plural': '2. 중고 굴삭기 관리'},
        ),
        migrations.AlterModelOptions(
            name='equipmentimage',
            options={'verbose_name': '장비 사진', 'verbose_name_plural': '3. 장비 사진 관리'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '사용자 프로필', 'verbose_name_plural': '1. 사용자 프로필 관리'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='listing_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='판매가격'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='password',
            field=models.CharField(max_length=100, verbose_name='비밀번호(수정용)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year_manufactured',
            field=models.IntegerField(verbose_name='제작년도'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment', verbose_name='해당 장비'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='image',
            field=models.ImageField(upload_to='equipment_images/', verbose_name='장비 사진'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='등록번호'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('PERSONAL', '개인'), ('DEALER', '매매상')], default='PERSONAL', max_length=10, verbose_name='사용자 유형'),
        ),
    ]
