# Generated by Django 5.2.9 on 2026-01-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_alter_equipment_options_alter_equipmentimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True, verbose_name='날짜')),
                ('count', models.IntegerField(default=0, verbose_name='방문자 수')),
            ],
            options={
                'verbose_name': '일별 방문자 수',
                'verbose_name_plural': '4. 방문자 통계',
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='아이피 주소')),
                ('visit_date', models.DateField(auto_now_add=True, verbose_name='방문 날짜')),
                ('referer', models.TextField(blank=True, null=True, verbose_name='유입 경로')),
            ],
            options={
                'verbose_name': '방문 상세 기록',
                'verbose_name_plural': '5. 방문 상세 로그',
                'constraints': [models.UniqueConstraint(fields=('ip_address', 'visit_date'), name='unique_visitor_ip_per_day')],
            },
        ),
    ]
