# Generated by Django 5.2.9 on 2026-01-05 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_visitorcount_visitorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorCount',
        ),
        migrations.DeleteModel(
            name='VisitorLog',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipmentimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='is_sold',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='business_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='equipment',
            name='month_manufactured',
            field=models.IntegerField(default=1, verbose_name='제작월'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='operating_hours',
            field=models.IntegerField(default=0, verbose_name='가동 시간(hr)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(max_length=100, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name='상세설명'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='listing_price',
            field=models.IntegerField(verbose_name='판매가격(만원)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='password',
            field=models.CharField(default='1234', max_length=20, verbose_name='수정비밀번호'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='image',
            field=models.ImageField(upload_to='equipment_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, default='PERSONAL', max_length=20, null=True),
        ),
    ]
