# Generated by Django 5.2.9 on 2026-01-05 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_delete_visitorcount_delete_visitorlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True, verbose_name='날짜')),
                ('count', models.IntegerField(default=0, verbose_name='방문자 수')),
            ],
            options={
                'verbose_name': '일별 방문자 수',
                'verbose_name_plural': '4. 방문자 통계',
            },
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': '중고 굴삭기', 'verbose_name_plural': '2. 중고 굴삭기 관리'},
        ),
        migrations.AlterModelOptions(
            name='equipmentimage',
            options={'verbose_name': '장비 사진', 'verbose_name_plural': '3. 장비 사진 관리'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '사용자 프로필', 'verbose_name_plural': '1. 사용자 프로필 관리'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='판매 완료 여부'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='등록번호'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='승인여부'),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='유튜브 채널 주소'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(max_length=100, verbose_name='현재 위치'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(verbose_name='상세 설명'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='listing_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='판매가격'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='password',
            field=models.CharField(max_length=100, verbose_name='비밀번호(수정용)'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment', verbose_name='해당 장비'),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='image',
            field=models.ImageField(upload_to='equipment_images/', verbose_name='장비 사진'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상호명'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('PERSONAL', '개인'), ('DEALER', '매매상')], default='PERSONAL', max_length=10, verbose_name='사용자 유형'),
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='아이피 주소')),
                ('visit_date', models.DateField(auto_now_add=True, verbose_name='방문 날짜')),
                ('referer', models.TextField(blank=True, null=True, verbose_name='유입 경로')),
            ],
            options={
                'verbose_name': '방문 상세 기록',
                'verbose_name_plural': '5. 방문 상세 로그',
                'unique_together': {('ip_address', 'visit_date')},
            },
        ),
    ]
