# Generated by Django 5.2.9 on 2026-01-26 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_visitorcount_alter_equipment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('HIRING', '사람구함'), ('SEEKING', '일자리구함')], default='HIRING', max_length=10, verbose_name='구분')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('location', models.CharField(max_length=100, verbose_name='지역')),
                ('equipment_type', models.CharField(max_length=100, verbose_name='필요장비/경력')),
                ('pay', models.CharField(max_length=100, verbose_name='급여/단가')),
                ('content', models.TextField(verbose_name='상세내용')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
