# Generated by Django 5.2.9 on 2026-01-29 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_jobpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUCKET', '바가지/버킷'), ('BREAKER', '뿌레카/함마'), ('GRAPPLE', '집게/그랩'), ('ETC', '기타 어테치먼트')], default='ETC', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('compatibility', models.CharField(help_text='예: 02급/06급 호환', max_length=100)),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
