# Generated by Django 5.2.9 on 2026-02-24 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_partimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='마감일'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='경력유무'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='writer_display',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='작성자(표시명)'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='상세내용'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='equipment_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='필요장비/경력'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='pay',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='급여/단가'),
        ),
    ]
