# Generated by Django 5.2.9 on 2026-02-25 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipment', '0016_jobpost_deadline_experience_writer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=50, verbose_name='이름(비회원)')),
                ('content', models.TextField(verbose_name='내용')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '댓글/문의',
                'verbose_name_plural': '댓글/문의',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='equipment.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '장비 찜',
                'verbose_name_plural': '장비 찜',
                'unique_together': {('user', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='PartFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='equipment.part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '부품 찜',
                'verbose_name_plural': '부품 찜',
                'unique_together': {('user', 'part')},
            },
        ),
    ]
