# Generated by Django 5.2.9 on 2026-02-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_add_favorite_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='수정/삭제용 비밀번호(해시)'),
        ),
    ]
