# Generated by Django 5.2.9 on 2026-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_jobpost_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='주소')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '부품점',
                'verbose_name_plural': '부품점(전국 연락처)',
                'ordering': ['region', 'name'],
            },
        ),
    ]
