# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_parts_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(
                choices=[
                    ('excavator', '굴삭기'),
                    ('forklift', '지게차'),
                    ('dump', '덤프'),
                    ('loader', '로더'),
                    ('attachment', '어태치먼트'),
                    ('etc', '기타(부품)'),
                ],
                default='excavator',
                help_text='굴삭기/지게차/덤프/로더/어태치먼트/기타(부품)',
                max_length=20,
                verbose_name='기종',
            ),
        ),
    ]
