# Generated by Django 5.2.9

from django.db import migrations, models


def truncate_description(apps, schema_editor):
    Equipment = apps.get_model('equipment', 'Equipment')
    for obj in Equipment.objects.exclude(description__isnull=True).exclude(description=''):
        if len(obj.description) > 50:
            obj.description = obj.description[:50]
            obj.save(update_fields=['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_add_equipment_type'),
    ]

    operations = [
        migrations.RunPython(truncate_description, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='상세 설명'),
        ),
    ]
