# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_alter_equipment_description_maxlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='비밀번호(수정용, 레거시)'),
        ),
    ]
