# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_equipment_password_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='listing_status',
            field=models.CharField(
                choices=[('NORMAL', '정상 노출'), ('EXPIRED_HIDDEN', '만료 숨김')],
                db_index=True,
                default='NORMAL',
                max_length=20,
                verbose_name='노출 상태',
            ),
        ),
    ]
