# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_equipment_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='모델명'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year_manufactured',
            field=models.IntegerField(blank=True, null=True, verbose_name='제작년도'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='month_manufactured',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='제작월'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='operating_hours',
            field=models.IntegerField(blank=True, default=0, verbose_name='가동 시간(hr)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='현재 위치'),
        ),
    ]
