# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0024_equipment_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='차량번호'),
        ),
    ]
