# Generated by Django 5.2.9 on 2026-03-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0026_alter_comment_object_id_alter_equipment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='region_sido',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='시/도'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='region_sigungu',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='시/군/구'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='지역(기타)'),
        ),
    ]
