# Generated by Django 5.2.9 on 2026-03-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0027_jobpost_region_sido_sigungu'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='회사명'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='deadline_type',
            field=models.CharField(blank=True, choices=[('DATE', '날짜'), ('UNTIL_FILLED', '채용시까지')], default='UNTIL_FILLED', max_length=20, verbose_name='마감 구분'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='doc_license',
            field=models.BooleanField(default=True, verbose_name='제출서류_면허증사본'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='doc_resident',
            field=models.BooleanField(default=True, verbose_name='제출서류_주민등록등본'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recruit_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='모집인원'),
        ),
    ]
