# Generated by Django 5.2.9 on 2026-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0028_job_post_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mast_type',
            field=models.CharField(blank=True, default='', help_text='지게차 전용: 2단/3단 등', max_length=10, verbose_name='마스트 타입'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='region_sido',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='시/도'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='region_sigungu',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='시/군/구'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sub_type',
            field=models.CharField(blank=True, default='', help_text='굴삭기: 타이어/크롤러/어태치먼트, 지게차: 디젤/전동/입식/LPG 등', max_length=20, verbose_name='세부 유형'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weight_class',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='중량 구분'),
        ),
    ]
