# Generated by Django 5.2.9 on 2026-03-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0029_equipment_mast_type_equipment_region_sido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='legacy_listing_id',
            field=models.PositiveIntegerField(blank=True, help_text='tb_pro.uid 이관 시 중복 방지·추적용', null=True, unique=True, verbose_name='기존(direct-nara) 매물 PK'),
        ),
        migrations.AddField(
            model_name='profile',
            name='legacy_member_id',
            field=models.PositiveIntegerField(blank=True, help_text='sw_member.mb_num 이관 시 중복 방지·추적용', null=True, unique=True, verbose_name='기존(direct-nara) 회원 PK'),
        ),
    ]
