# Generated by Django 5.2.9 on 2026-03-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0030_add_legacy_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='legacy_listing_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='legacy_member_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='유료 회원 여부'),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_until',
            field=models.DateField(blank=True, null=True, verbose_name='유료 만료일'),
        ),
    ]
