# Generated by Django 5.2.9 on 2026-03-14 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0031_add_profile_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_bumped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 끌어올리기 시각'),
        ),
        migrations.CreateModel(
            name='DeletedListingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='모델명')),
                ('image_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='대표 사진 해시')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='삭제 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_listing_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '삭제 매물 로그(재등록 제한)',
                'verbose_name_plural': '삭제 매물 로그(재등록 제한)',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
