# Generated by Django 5.2.9 on 2026-03-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0032_bump_and_deleted_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='legacy_listing_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='(이관) 기존 매물 PK'),
        ),
        migrations.AddField(
            model_name='profile',
            name='legacy_member_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='(이관) 기존 회원 PK'),
        ),
    ]
