# Generated by Django 5.2.9 on 2026-03-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0033_restore_legacy_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='휴대폰 본인인증 여부'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='휴대폰 인증 시각'),
        ),
    ]
