# Generated by Django 5.2.9 on 2026-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0034_add_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('excavator', '굴삭기'), ('forklift', '지게차'), ('dump', '덤프트럭'), ('loader', '로더/휠로더'), ('crane', '크레인'), ('attachment', '어태치먼트'), ('etc', '기타(부품)'), ('other', '기타 중장비')], default='excavator', help_text='굴삭기/지게차/덤프/로더/어태치먼트/기타(부품)', max_length=20, verbose_name='기종'),
        ),
    ]
