# Generated by Django 5.2.9 on 2026-03-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0036_remove_etc_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='legacy_guin_uid',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='(이관) 구인구직 UID'),
        ),
    ]
