# Generated by Django 5.2.9 on 2026-04-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0037_jobpost_legacy_guin_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ownership_claimed_at',
            field=models.DateTimeField(blank=True, help_text='가입자가 내 매물 찾기로 본인 계정에 연결한 시각', null=True, verbose_name='소유권 연결 시각'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unclaimed_phone_norm',
            field=models.CharField(blank=True, db_index=True, default='', help_text='기존 매물만 남길 때 등록 연락처. 숫자만 저장해 프로필 전화와 매칭합니다.', max_length=20, verbose_name='미연결 연락처(숫자만)'),
        ),
    ]
