# Generated by Django 5.2.9 on 2026-04-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0041_profile_withdraw_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentEquipment',
            fields=[
            ],
            options={
                'verbose_name': '어태치먼트 매물',
                'verbose_name_plural': '2-6. 어태치먼트 매물 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('equipment.equipment',),
        ),
        migrations.CreateModel(
            name='CraneEquipment',
            fields=[
            ],
            options={
                'verbose_name': '크레인 매물',
                'verbose_name_plural': '2-5. 크레인 매물 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('equipment.equipment',),
        ),
        migrations.CreateModel(
            name='DumpEquipment',
            fields=[
            ],
            options={
                'verbose_name': '덤프트럭 매물',
                'verbose_name_plural': '2-3. 덤프트럭 매물 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('equipment.equipment',),
        ),
        migrations.CreateModel(
            name='ExcavatorEquipment',
            fields=[
            ],
            options={
                'verbose_name': '굴삭기 매물',
                'verbose_name_plural': '2-1. 굴삭기 매물 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('equipment.equipment',),
        ),
        migrations.CreateModel(
            name='ForkliftEquipment',
            fields=[
            ],
            options={
                'verbose_name': '지게차 매물',
                'verbose_name_plural': '2-2. 지게차 매물 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('equipment.equipment',),
        ),
        migrations.CreateModel(
            name='LoaderEquipment',
            fields=[
            ],
            options={
                'verbose_name': '스키로더/로더 매물',
                'verbose_name_plural': '2-4. 스키로더/로더 매물 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('equipment.equipment',),
        ),
        migrations.CreateModel(
            name='OtherEquipment',
            fields=[
            ],
            options={
                'verbose_name': '기타 중장비 매물',
                'verbose_name_plural': '2-7. 기타 중장비 매물 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('equipment.equipment',),
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'verbose_name': '구인구직', 'verbose_name_plural': '구인구직'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': '부품', 'verbose_name_plural': '부품'},
        ),
        migrations.AlterModelOptions(
            name='partimage',
            options={'verbose_name': '부품 사진', 'verbose_name_plural': '부품 사진'},
        ),
        migrations.AddField(
            model_name='partsshop',
            name='equipment_types',
            field=models.JSONField(blank=True, default=list, verbose_name='취급 장비'),
        ),
        migrations.AddField(
            model_name='partsshop',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='partsshop',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='partsshop',
            name='manufacturer',
            field=models.JSONField(blank=True, default=list, verbose_name='취급 제조사'),
        ),
        migrations.AddField(
            model_name='partsshop',
            name='shop_kind',
            field=models.CharField(choices=[('as', 'AS센터'), ('parts', '부품점')], default='parts', max_length=20, verbose_name='업체 유형'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('excavator', '굴삭기'), ('forklift', '지게차'), ('dump', '덤프트럭'), ('loader', '스키로더/로더'), ('crane', '크레인'), ('attachment', '어태치먼트'), ('other', '기타 중장비')], default='excavator', help_text='굴삭기/지게차/덤프/로더/어태치먼트/기타(부품)', max_length=20, verbose_name='기종'),
        ),
    ]
