# Generated by Django 5.2.9 on 2026-04-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0042_attachmentequipment_craneequipment_dumpequipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('youtube_url', models.URLField(verbose_name='유튜브 URL')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='설명')),
                ('purpose', models.CharField(choices=[('all', '전체'), ('repair', '수리·정비'), ('buying', '구매가이드'), ('review', '기종리뷰'), ('safety', '사고예방')], default='all', max_length=20, verbose_name='목적')),
                ('equipment_type', models.CharField(choices=[('all', '전체'), ('excavator', '굴삭기'), ('forklift', '지게차'), ('dump', '덤프트럭'), ('loader', '스키로더·로더'), ('crane', '크레인'), ('attachment', '어태치먼트')], default='all', max_length=20, verbose_name='기종')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '유튜브 콘텐츠',
                'verbose_name_plural': '유튜브 콘텐츠',
                'ordering': ['sort_order', '-created_at', '-id'],
            },
        ),
    ]
