# Generated by Django 5.2.9 on 2026-04-26 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0043_youtubecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedlistinglog',
            name='equipment_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='기종'),
        ),
        migrations.AddField(
            model_name='deletedlistinglog',
            name='listing_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=12, null=True, verbose_name='가격'),
        ),
        migrations.AddField(
            model_name='deletedlistinglog',
            name='year_manufactured',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='연식'),
        ),
        migrations.CreateModel(
            name='EquipmentBumpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bumped_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='끌어올리기 시각')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bump_logs', to='equipment.equipment', verbose_name='매물')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bump_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '매물 끌어올리기 로그',
                'verbose_name_plural': '매물 끌어올리기 로그',
                'ordering': ['-bumped_at'],
            },
        ),
    ]
