# Generated by Django 5.2.9 on 2026-04-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0044_deletedlistinglog_equipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('BUCKET', '바가지/버킷'), ('BREAKER', '뿌레카/함마'), ('GRAPPLE', '집게'), ('ROTLINK', '회전링크'), ('AUGER', '오거/드릴'), ('ETC', '기타')], default='ETC', max_length=20),
        ),
    ]
