# Generated by Django 5.2.9 on 2026-04-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0045_alter_part_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
