# Generated by Django 5.2.9 on 2026-04-28 07:58

from django.db import migrations


def forwards_copy_manufacturer_to_manufacturers(apps, schema_editor):
    PartsShop = apps.get_model("equipment", "PartsShop")
    for shop in PartsShop.objects.all():
        if shop.manufacturers:
            continue

        raw = shop.manufacturer
        values = []

        if isinstance(raw, list):
            values = [str(x).strip() for x in raw if str(x).strip()]
        elif isinstance(raw, str):
            # "현대, 두산" -> ["현대", "두산"]
            values = [x.strip() for x in raw.split(",") if x.strip()]
        elif raw:
            values = [str(raw).strip()]

        if values:
            # 중복 제거 + 순서 유지
            deduped = list(dict.fromkeys(values))
            shop.manufacturers = deduped
            shop.save(update_fields=["manufacturers"])


def backwards_copy_manufacturers_to_manufacturer(apps, schema_editor):
    PartsShop = apps.get_model("equipment", "PartsShop")
    for shop in PartsShop.objects.all():
        raw = shop.manufacturers or []
        if not raw:
            continue

        if isinstance(raw, list):
            values = [str(x).strip() for x in raw if str(x).strip()]
            joined = ", ".join(values)
        else:
            joined = str(raw).strip()

        if joined:
            shop.manufacturer = joined
            shop.save(update_fields=["manufacturer"])


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0047_partsshop_manufacturers_partsshop_repair_types_and_more'),
    ]

    operations = [
        migrations.RunPython(
            forwards_copy_manufacturer_to_manufacturers,
            backwards_copy_manufacturers_to_manufacturer,
        ),
    ]
