# Generated by Django 5.2.9 on 2026-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0048_auto_20260428_1658"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsshop",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0, help_text="0.0~5.0", max_digits=2, verbose_name="평점"),
        ),
        migrations.AddField(
            model_name="partsshop",
            name="review_count",
            field=models.PositiveIntegerField(default=0, verbose_name="리뷰 수"),
        ),
    ]
