# Generated by Django 5.2.9 on 2026-04-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0049_partsshop_rating_review_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceConsultation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("applicant_name", models.CharField(max_length=50, verbose_name="신청자 이름")),
                ("contact", models.CharField(max_length=20, verbose_name="연락처")),
                ("desired_equipment", models.CharField(max_length=100, verbose_name="희망 장비")),
                ("budget_manwon", models.PositiveIntegerField(verbose_name="구입 예산(만원)")),
                ("desired_months", models.PositiveSmallIntegerField(verbose_name="희망 할부기간(개월)")),
                ("memo", models.CharField(blank=True, default="", max_length=300, verbose_name="메모")),
                ("status", models.CharField(choices=[("WAITING", "대기중"), ("CONTACTED", "연락완료"), ("CONTRACTED", "계약완료"), ("CANCELLED", "취소")], db_index=True, default="WAITING", max_length=12, verbose_name="처리상태")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="신청일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
            ],
            options={
                "verbose_name": "할부 상담 신청",
                "verbose_name_plural": "할부 상담 신청 내역",
                "ordering": ["-created_at"],
            },
        ),
    ]
