# Generated by Django 5.2.9 on 2026-03-01 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0026_alter_comment_object_id_alter_equipment_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 메시지 시각')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_as_buyer', to=settings.AUTH_USER_MODEL, verbose_name='구매자(문의자)')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='equipment.equipment', verbose_name='매물')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방',
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일시')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='채팅방')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('equipment', 'buyer', 'seller'), name='unique_equipment_buyer_seller'),
        ),
    ]
