# Generated by Django 5.2.9 on 2026-03-02 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('equipment', '0026_alter_comment_object_id_alter_equipment_author_and_more'),
        ('soil', '0001_soil_post_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroom',
            name='unique_equipment_buyer_seller',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='soil_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='soil.soilpost', verbose_name='흙 게시글'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='equipment.equipment', verbose_name='매물'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('equipment', 'buyer', 'seller'), name='unique_equipment_buyer_seller'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('soil_post__isnull', False)), fields=('soil_post', 'buyer', 'seller'), name='unique_soil_post_buyer_seller'),
        ),
    ]
