# Generated by Django 5.2.9 on 2026-03-02 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_soil_post_room'),
        ('equipment', '0028_job_post_extra_fields'),
        ('soil', '0001_soil_post_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='equipment.jobpost', verbose_name='구인구직 글'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('job_post__isnull', False)), fields=('job_post', 'buyer', 'seller'), name='unique_job_post_buyer_seller'),
        ),
    ]
