# Generated by Django 5.2.9 on 2026-02-23 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='등급명')),
                ('is_paid', models.BooleanField(default=False, verbose_name='유료등급')),
                ('max_listings', models.PositiveIntegerField(blank=True, help_text='null이면 제한 없음', null=True, verbose_name='최대 매물 수')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '회원 등급',
                'verbose_name_plural': '회원 등급',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='상호/회사명')),
                ('biz_no', models.CharField(blank=True, max_length=20, verbose_name='사업자번호')),
                ('ceo_name', models.CharField(blank=True, max_length=50, verbose_name='대표자명')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='추가 연락처')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('is_dealer', models.BooleanField(default=False, help_text='매매상(정액제) 여부 캐시', verbose_name='매매상 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.membershipgrade', verbose_name='등급')),
            ],
            options={
                'verbose_name': '회원 프로필',
                'verbose_name_plural': '회원 프로필',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', '월 구독'), ('yearly', '연 구독')], max_length=20, verbose_name='요금제')),
                ('started_at', models.DateTimeField(verbose_name='시작일')),
                ('expires_at', models.DateTimeField(verbose_name='만료일')),
                ('status', models.CharField(choices=[('active', '이용중'), ('expired', '만료'), ('cancelled', '취소')], default='active', max_length=20, verbose_name='상태')),
                ('pg_provider', models.CharField(blank=True, max_length=50, verbose_name='PG사')),
                ('pg_uid', models.CharField(blank=True, max_length=100, verbose_name='PG 결제고유번호')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='결제금액(원)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.memberprofile', verbose_name='회원')),
            ],
            options={
                'verbose_name': '구독',
                'verbose_name_plural': '구독',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='금액(원)')),
                ('pg_provider', models.CharField(blank=True, max_length=50, verbose_name='PG사')),
                ('pg_uid', models.CharField(blank=True, max_length=100, verbose_name='PG 고유번호')),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패'), ('refunded', '환불')], max_length=20, verbose_name='상태')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.memberprofile', verbose_name='회원')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.subscription', verbose_name='구독')),
            ],
            options={
                'verbose_name': '결제 이력',
                'verbose_name_plural': '결제 이력',
                'ordering': ['-created_at'],
            },
        ),
    ]
