# Generated by Django 5.2.9 on 2026-03-02 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('need', '흙 받으실분'), ('offer', '흙 드립니다')], default='need', max_length=10, verbose_name='유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('location', models.CharField(max_length=100, verbose_name='지역')),
                ('quantity', models.CharField(blank=True, max_length=200, verbose_name='수량')),
                ('soil_type', models.CharField(blank=True, max_length=100, verbose_name='흙 종류')),
                ('description', models.TextField(blank=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '흙 게시글',
                'verbose_name_plural': '흙 게시글',
                'ordering': ['-created_at'],
            },
        ),
    ]
