# Generated by Django 5.2.9 on 2026-04-23 12:43

from django.db import migrations, models


def forwards_map_post_type(apps, schema_editor):
    SoilPost = apps.get_model('soil', 'SoilPost')
    SoilPost.objects.filter(post_type='need').update(post_type='take')
    SoilPost.objects.filter(post_type='offer').update(post_type='give')


def backwards_map_post_type(apps, schema_editor):
    SoilPost = apps.get_model('soil', 'SoilPost')
    SoilPost.objects.filter(post_type='take').update(post_type='need')
    SoilPost.objects.filter(post_type='give').update(post_type='offer')


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_soil_post_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soilpost',
            options={'ordering': ['-created_at'], 'verbose_name': '현장 자재 글', 'verbose_name_plural': '현장 자재 글'},
        ),
        migrations.AddField(
            model_name='soilpost',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='연락처'),
        ),
        migrations.AddField(
            model_name='soilpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='soil_posts/', verbose_name='사진'),
        ),
        migrations.AddField(
            model_name='soilpost',
            name='material_type',
            field=models.CharField(choices=[('soil', '흙·토사'), ('sand', '모래'), ('gravel', '자갈'), ('crushed', '잔석·쇄석'), ('block', '블록·벽돌'), ('concrete', '콘크리트 잔재'), ('other', '기타 자재')], default='soil', max_length=20, verbose_name='자재 유형'),
        ),
        migrations.AddField(
            model_name='soilpost',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='soilpost',
            name='description',
            field=models.TextField(blank=True, verbose_name='상세내용'),
        ),
        migrations.AlterField(
            model_name='soilpost',
            name='post_type',
            field=models.CharField(choices=[('give', '나눔 (드립니다)'), ('take', '수거 (가져가실분)')], default='give', max_length=10, verbose_name='게시 유형'),
        ),
        migrations.RunPython(forwards_map_post_type, backwards_map_post_type),
        migrations.AlterField(
            model_name='soilpost',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, verbose_name='수량'),
        ),
    ]
